version: '3.5'
services:
  consul:
    image: consul:latest
    command: agent -server -ui -node=server1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - consul-net

  gateway-service:
    restart: on-failure
    build: gateway-service/.
    image: spring-reactive-web/gateway-service:1
    ports:
      - "8000:8000"
    networks:
      - consul-net
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500

  otp-handler-service:
    restart: on-failure
    build: otp-handler-service/.
    image: spring-reactive-web/otp-handler-service:1
    volumes:
      - F://CodeBase//Intellij//spring-reactive-web//logs:/home/otp/logs
    ports:
      - "8001:8001"
    networks:
      - consul-net
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=test
      - POSTGRES_USER=jai
      - POSTGRES_PASSWORD=passepartout
      - NOTIFICATION_SERVICE_HOST=notification-service
      - NOTIFICATION_SERVICE_PORT=8005
      - NUMBER_INFORMATION_SERVICE_HOST=number-information-service
      - NUMBER_INFORMATION_SERVICE_PORT=8006
      - JAEGER_HOST=jaeger

  customer-service:
    restart: on-failure
    build: customer-service/.
    image: spring-reactive-web/customer-service:1
    ports:
      - "8002:8002"
    networks:
      - consul-net
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=test
      - POSTGRES_USER=jai
      - POSTGRES_PASSWORD=passepartout
      - JAEGER_HOST=jaeger

  notification-service:
    restart: on-failure
    build: notification-service/.
    image: spring-reactive-web/notification-service:1
    ports:
      - "8005:8005"
    networks:
      - consul-net

  number-information-service:
    restart: on-failure
    build: number-information-service/.
    image: spring-reactive-web/number-information-service:1
    ports:
      - "8006:8006"
    networks:
      - consul-net

  postgres:
    image: postgres:latest
    restart: always
    networks:
      - consul-net
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: jai
      POSTGRES_PASSWORD: passepartout
    ports:
      - "5432:5432"

  jaeger:
    image: jaegertracing/all-in-one:1.8
    ports:
      - "16686:16686"
      - "9411:9411"
    networks:
      - consul-net
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

networks:
  consul-net:
    driver: bridge