server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: ${consul.host:localhost}
      port: ${consul.port:8500}
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: otp-handler-service
          uri: lb://otp-handler-service
          predicates:
            - Path=/otp-handler-service/**
          filters:
            - StripPrefix=1
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: [ "*" ]
            allowedMethods: [ "POST","GET","PUT", "DELETE" ]
            allowedHeaders: "*"
            allowCredentials: true
manegement:
  endpoints:
    web:
      exposure:
        include: "*"